name: Memory leak
description: Memory leak caused by TAB.
labels: ["Type: Memory leak"]
body:
  - type: input
    attributes:
      label: Server version
      description: Version and type of used server software where TAB is installed.
      placeholder: Spigot 1.18.1
    validations:
      required: true

  - type: input
    attributes:
      label: TAB version
      description: Full version in numbers, "latest" is not a version.
      placeholder: 3.0.2
    validations:
      required: true

  - type: textarea
    attributes:
      label: Heap dump
      description: Link to uploaded memory dump which I can look into.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Uncleared object(s)
      description: Objects you believe should have been removed from the memory but are not
      placeholder: |
        There is only 1 player online, but heap dump has 100 instances of TabPlayer
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional info
      description: Any other info you want to provide.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Let's make sure this report is valid
      options:
        - label: I am running latest version of the plugin
          required: true
        - label: I have included download link of my heap dump
          required: true
        - label: I ticked all of the boxes without actually reading them
          required: false
        - label: I have explained what I believe is wrong with the heap dump
          required: true